# [Choice] Alpine version: 3.16, 3.17, 3.18, 3.19
ARG VARIANT
FROM mcr.microsoft.com/devcontainers/base:alpine-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
